---
title: "Exercises"
format:
  html:
    self-contained: true
    theme: cosmo
---

Each exercise should include references to help docs and/or notes document?
Add "solutions" / hints for exercises? Can be made so that text/code is hidden I think

## Exercise 1.0.0 - Motivation

Might make sense that the very first exercise involves 


## Exercise 1.1.0 - Configure your Git profile

Should probably require people do this beforeheand as part of preparing for the seminar?
But maybe there should be some more advanced exercises on this topic at some other point in
the seminar?

## Exercise 1.2.1 - Initatiate a Git repository

## Exercise 1.2.2 - Commit code

## Clone a Git repository from GitHub

Clone the repository used to make these exercises. It can be found at
[https://github.com/thomas-rasmussen/introduction-to-git](https://github.com/thomas-rasmussen/introduction-to-git)


::: {.callout-tip collapse=true appearance="simple"}
## Hint 1

Press the green "Code" button for help on how to clone the repository using different approaches.
:::

Hint 2: The easiest way to clone the repository is using HTTPS

Solution: Cloning the repository (in your current work directory) using HTTPS: 

git clone "https://github.com/thomas-rasmussen/introduction-to-git.git"

## Make a (local) remote for a repository